import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { AuthProvider } from '@/context/AuthProvider';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AuthProvider>
				<body className={cn('min-h-screen scroll-smooth bg-background font-sans antialiased', inter.className)}>
					<main className="relative flex min-h-screen flex-col">
						<div className="mx-auto max-w-3xl h-full px-4 sm:px-6 lg:max-w-7xl lg:px-8">{children}</div>
					</main>
					<Toaster />
				</body>
			</AuthProvider>
		</html>
	);
}
