import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { AuthProvider } from '@/context/AuthProvider';
import { Toaster } from '@/components/ui/toaster';
import { ThemeProvider } from '@/components/shared/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<AuthProvider>
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
					<body className={cn('min-h-screen scroll-smooth bg-background font-sans antialiased', inter.className)}>
						<main className="relative flex min-h-screen flex-col">
							<div className="h-full px-4 sm:px-6 lg:px-8">{children}</div>
						</main>
						<Toaster />
					</body>
				</ThemeProvider>
			</AuthProvider>
		</html>
	);
}
